import { NextResponse } from "next/server"

const resources = [
  // Stress and Anxiety
  {
    id: 1,
    title: "How to manage anxiety",
    category: "Stress and Anxiety",
    type: "Video",
    description: "Expert tips on how to recognise, manage and minimise anxiety.",
    url: "https://youtu.be/mXlV8OVvrD8?si=mHGRnFke57z22aBJ",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/mXlV8OVvrD8?si=mHGRnFke57z22aBJ&start=1",
  },
  {
    id: 2,
    title: "How to stop feeling anxious about anxiety",
    category: "Stress and Anxiety",
    type: "Video",
    description: "Tim, a remedial hypnotist, explains why we need to think about anxiety differently and how a simple shift in thinking can help us feel less anxious.",
    url: "https://youtu.be/ZidGozDhOjg?si=iWWPDMPJVTv28KYA",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/ZidGozDhOjg?si=bbqKgD7DueYjVccJ&start=1",
  },
  {
    id: 3,
    title: "Tips to Manage Anxiety & Panic Attacks",
    category: "Stress and Anxiety",
    type: "Video",
    description: "Dr. Jennie Byrne gives 3 tips to help you manage your anxiety and panic attacks.",
    url: "https://youtu.be/zQRSPHhT3C0?si=hxyFEaleEUPykN4C",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/zQRSPHhT3C0?si=hxyFEaleEUPykN4C&start=1",
  },
  {
    id: 4,
    title: "How to cope with anxiety",
    category: "Stress and Anxiety",
    type: "Video",
    description: "Olivia Remes from the University of Cambridge shares ways to treat and manage anxiety, emphasizing the importance of harnessing strength in ourselves.",
    url: "https://youtu.be/WWloIAQpMcQ?si=2BCDGh-CEVt5TtFp",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/WWloIAQpMcQ?si=2BCDGh-CEVt5TtFp&start=1",
  },
  {
    id: 5,
    title: "7 Proven Ways To Manage Anxiety",
    category: "Stress and Anxiety",
    type: "Video",
    description: "7 simple ways to manage your anxiety, providing tips, tricks, techniques and management skills so that anxiety doesn't dominate your life.",
    url: "https://youtu.be/whrN7ujh3Yk?si=YkjoAFr_EMjXtMxA",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/whrN7ujh3Yk?si=YkjoAFr_EMjXtMxA&start=1",
  },
  {
    id: 6,
    title: "How to deal with Depression and Anxiety?| Hindi",
    category: "Stress and Anxiety",
    type: "Video",
    description: "Sandeep Maheshwari shares his journey of struggling, failing and surging ahead in search of success, happiness and contentment.",
    url: "https://youtu.be/eAK14VoY7C0?si=nCWihoioedHweH4d",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/eAK14VoY7C0?si=nCWihoioedHweH4d&start=1",
  },

  // Depression
  {
    id: 7,
    title: "Ways to Cope With Depression",
    category: "Depression",
    type: "Video",
    description: "Four ways to cope with depression that can make a real difference in your daily life, whether you're dealing with it yourself or supporting a loved one.",
    url: "https://youtu.be/gyQX6bU1NIY?si=uL-_PCdjb3P8bb55",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/gyQX6bU1NIY?si=uL-_PCdjb3P8bb55",
  },
  {
    id: 8,
    title: "Lies Depression Tells You - Depression Motivation, it gets better",
    category: "Depression",
    type: "Video",
    description: "Depression is a liar that warps your perception. Learn 5 of the biggest lies depression tells—and the truth behind them.",
    url: "https://youtu.be/uq2C8us969M?si=gRRycRkWL-tXFS0j",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/uq2C8us969M?si=gRRycRkWL-tXFS0j",
  },
  {
    id: 9,
    title: "How To Deal With Depression?",
    category: "Depression",
    type: "Video",
    description: "It is not suffering that makes us negative, but our perspective on it. Practice Cittanupassana (Contemplation on the mind and thoughts).",
    url: "https://youtu.be/TEwoWxLwCfA?si=WsUA7qDUMPgJi90c",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/TEwoWxLwCfA?si=WsUA7qDUMPgJi90c",
  },
  {
    id: 10,
    title: "How to deal with Depression and Anxiety? | Hindi",
    category: "Depression",
    type: "Video",
    description: "Sandeep Maheshwari shares his journey of struggling, failing and surging ahead in search of success, happiness and contentment.",
    url: "https://youtu.be/eAK14VoY7C0?si=SNCwhrRBjiu5DhTw",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/eAK14VoY7C0?si=SNCwhrRBjiu5DhTw",
  },

  // Sleep Disorders (Insomnia)
  {
    id: 11,
    title: "What causes insomnia? - Dan Kwartler",
    category: "Sleep Disorders (Insomnia)",
    type: "Video",
    description: "Dan Kwartler details the science of insomnia, the world’s most common sleep disorder, and explains the unsolvable loop at its heart.",
    url: "https://youtu.be/j5Sl8LyI7k8?si=eiKWTEyTGOGvFwH2",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/j5Sl8LyI7k8?si=eiKWTEyTGOGvFwH2",
  },
  {
    id: 12,
    title: "Ways To Cure Insomnia Naturally",
    category: "Sleep Disorders (Insomnia)",
    type: "Video",
    description: "Sleep expert Dr. Michael Breus explains some of the best ways to treat insomnia naturally, which are proven more effective than medication.",
    url: "https://youtu.be/tIq3AGBXTwQ?si=l1V-eWuJF_52_GgO",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/tIq3AGBXTwQ?si=l1V-eWuJF_52_GgO",
  },
  {
    id: 13,
    title: "How to Evaluate and Treat SLEEP PROBLEMS and INSOMNIA?",
    category: "Sleep Disorders (Insomnia)",
    type: "Video",
    description: "Dr Sanil Rege, Consultant Psychiatrist, explains the evaluation of sleep difficulties using a practical algorithm.",
    url: "https://youtu.be/Rrdx11rDa9o?si=oivZ0AUbPBlTreJL",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/Rrdx11rDa9o?si=oivZ0AUbPBlTreJL",
  },
  {
    id: 14,
    title: "Anti-Anxiety and Sleep Point",
    category: "Sleep Disorders (Insomnia)",
    type: "Video",
    description: "Anti-Anxiety and Sleep Point! by Dr. Mandell",
    url: "https://youtu.be/YQ-4sQ_UD8g?si=WXotbpTEpR4off22",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/YQ-4sQ_UD8g?si=WXotbpTEpR4off22",
  },
  {
    id: 15,
    title: "Sleep Disorders: Troubled by not being able to sleep through the night? Know the remedies of Healthy Sleep | Hindi",
    category: "Sleep Disorders (Insomnia)",
    type: "Video",
    description: "A healthy and deep sleep is an essential element of life which is as important as water and food for everyone.",
    url: "https://youtu.be/sr92pqPOJwg?si=PiBLntPjrtaTb1uq",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/sr92pqPOJwg?si=PiBLntPjrtaTb1uq",
  },

  // Lust
  {
    id: 16,
    title: "Ways to STOP porn addiction",
    category: "Lust",
    type: "Video",
    description: "Learn five ways to break out of porn and masturbation addiction, including identifying triggers, cleaning up social media, and replacing the habit with healthy activities.",
    url: "https://youtu.be/Bw47gpm0doU?si=J9KCQ-ZyutfEnM6c",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/Bw47gpm0doU?si=J9KCQ-ZyutfEnM6c",
  },
  {
    id: 17,
    title: "Information on masterbation",
    category: "Lust",
    type: "Video",
    description: "Various information and misconceptions about masturbation.",
    url: "https://youtu.be/PjDXhs4Zi24?si=ybo2PAulMTtFXC8J",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/PjDXhs4Zi24?si=ybo2PAulMTtFXC8J",
  },
  {
    id: 18,
    title: "5 Steps to Kill Lust Forever",
    category: "Lust",
    type: "Video",
    description: "Learn a powerful 5 step system to escape lust, porn addiction, and dopamine overload, and take back control of your mind, energy, and life.",
    url: "https://youtu.be/lFFZhAIrvcc?si=MM6nVFklreHiNTFR",
    duration: "Video",
    isEmbed: true,
    embedUrl: "https://www.youtube.com/embed/lFFZhAIrvcc?si=MM6nVFklreHiNTFR",
  },
]

export async function GET() {
  try {
    return NextResponse.json(resources)
  } catch (error) {
    console.error("Error fetching resources:", error)
    return NextResponse.json({ error: "Failed to fetch resources" }, { status: 500 })
  }
}
